### ISSUE TITLE
Sample projects not using any Lock version at all

### ISSUE THREAD

**Issue by mikearias3** [auth0-samples/auth0-ios-swift-sample#33]
*Environment Information*
Browser: Google Chrome v58.0.3029.96 (64-bit)
Sample: All samples under https://github.com/auth0-samples/auth0-ios-swift-sample
Xcode: 8.2.1

*Description*
At the moment, all the sample projects are not using any Lock version.

*Screenshot*
<img width="430" alt="screen shot 2017-06-13 at 10 51 16 pm" src="https://user-images.githubusercontent.com/5594487/27113962-503d7b34-508e-11e7-918d-4269761a4cd1.png">

**Comment by dotmat** [comment]
Hi @cocojoe Any more info on using Lock with iOS?

**Comment by cocojoe** [comment]
Well this is because [HLP](https://auth0.com/docs/hosted-pages/login) is the preferred method which only requires `Auth0.swift`.  However, for embedded Lock you can check out the [Embedded-Login Branch](https://github.com/auth0-samples/auth0-ios-swift-sample/tree/embedded-login)
