### ISSUE TITLE
07-linking-accounts sample not building

### ISSUE THREAD

**Issue by mikearias3** [auth0-samples/auth0-ios-swift-sample#34]
*Environment Information*
Browser: Google Chrome v58.0.3029.96 (64-bit)
Sample: https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/07-Linking-Accounts
Xcode: 8.2.1

*Description*
A Shell Script Invocation Error is preventing the 07 sample to build.

*Screenshot*
<img width="1016" alt="screen shot 2017-07-04 at 9 39 15 pm" src="https://user-images.githubusercontent.com/5594487/27845958-96e59886-6101-11e7-9d14-b1bad0eb2312.png">

**Comment by cocojoe** [comment]
This should be fixed btw, there was an issue with downloaded samples having their permissions overwritten. If you chance that file to executable it would be okay `chmod 755 filename`.
