### ISSUE TITLE
Access Token is not in JWT format.

### ISSUE THREAD

**Issue by yfujiki** [auth0-samples/auth0-ios-swift-sample#39]
I just downloaded the sample from official repo (https://github.com/auth0-samples/auth0-ios-swift-sample/) and ran with updated Auth0.plist.

So, the code snippet is something like this 

            Auth0
                .webAuth()
                .audience("https://" + clientInfo.domain + "/userinfo")
                .scope("openid profile")
                .start {
                    switch $0 {
                    case .failure(let error):
                        // Handle the error
                        print("Error: \(error)")
                    case .success(let credentials):
                        guard let accessToken = credentials.accessToken, let idToken = credentials.idToken else { return } ...

It works fine and lets me log in, but the `accessToken` is not JWT. Something very short like `KBSxkmG-OcpA6-cg`.

**Comment by chenkie** [comment]
Access tokens will come back as opaque strings unless an API identifier is set as the audience. Read through the Calling APIs quickstart for how to set up an API in Auth0 API https://auth0.com/docs/quickstart/native/ios-swift/04-calling-apis

**Comment by yfujiki** [comment]
I see. Thanks, I finally understood what audience is...
