### ISSUE TITLE
API call throwing error because of placeholder

### ISSUE THREAD

**Issue by mikearias3** [auth0-samples/auth0-ios-swift-sample#40]
**Environment Information**
Browser: Google Chrome v60 for Mac
Sample: https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/04-Calling-APIs
Xcode: 8.3.2

**Description**
After the user builds, runs the sample and logs in, if he clicks on any of the 2 "Call API" buttons the app throws a fatal error saying: `fatal error: unexpectedly found nil while unwrapping an Optional value`

**Screenshot**
<img width="455" alt="screen shot 2017-08-17 at 9 12 48 pm" src="https://user-images.githubusercontent.com/5594487/29440543-e228a5f4-8393-11e7-87e6-248b6d88e1ec.png">

**Comment by cocojoe** [comment]
This is supposed to be replaced by the user's own URL value, that being said I would rather avoid a crash and will replace with a valid looking url that implies the same thing.

**Comment by cocojoe** [comment]
Was fixed in #42
