### ISSUE TITLE
Display Registration screen with Universal WebAuth?

### ISSUE THREAD

**Issue by f-gonzalez** [auth0-samples/auth0-ios-swift-sample#54]
The Universal login page contains both login and registration in the same screen (divided with tabs). Suppose I want to have two buttons in the app, one for login and another one for registration, it is possible to add some parameter to the webAuth() method to open the web page showing directly the registration screen (its the same screen but with that tab already selected)? 

Auth0
            .webAuth()
            .scope()
            .audience()
            .start {

**Comment by jimmyjames** [comment]
Hi @f-gonzalez, if you're still interested in this issue, it's best discussed in the [Auth0.Swift Repo](https://github.com/auth0/Auth0.swift). I don't _think_ it's possible, but opening an issue there to discuss further will be the past path forward.
