### ISSUE TITLE
Sign out is not clearing user data.

### ISSUE THREAD

**Issue by jigarpatel17** [auth0-samples/auth0-ios-swift-sample#57]
Thanks for providing support for native platforms(Android and iOS). 

OS: iOS (Mobile app)

Using login with Google, at the time of sign out, it's not clearing the data. And then If I try to login again with Google, it does not ask for Gmail account to process with google login and even get data as well. And same thing is not working after uninstalling. 

Even tried to clear data of cookie but it still not working.

Please help to fix this. Thanks

**Comment by cocojoe** [comment]
You are using `clearSession(federated: true)` to clear the session

**Comment by jigarpatel17** [comment]
@cocojoe Thanks for quick response,.

Tried with your suggested as well, but still getting same issue.
