### ISSUE TITLE
iOS Simulators

### ISSUE THREAD

**Issue by sbanil** [auth0-samples/auth0-ios-swift-sample#62]
Sample App doesn't work in iOS simulators (iPhone 11 Pro). Is there a setting that should be enabled to make it work in simulators for developer unit testing?

**Comment by cocojoe** [comment]
Can you be more specific, what in particular doesn't work? How do we recreate your scenario.  Thanks

**Comment by sbanil** [comment]
1. Logon using the sample app
2. See a success message with token
3. close the simulator
4. bring it back up , see the home view controller with sign in
5. click sign in , SFViewController launches
6. Get prompt "00-Login" wants to use "auth0.com" sign in
7. Click Continue 
8. Get the same prompt "00-Login" wants to use "auth0.com" sign in. Authentication never finishes.
9. I also tried using Device and after first authentication , even after removing app and reinstalling doesn't seem to fix it.

**Comment by sbanil** [comment]
video of the issue: https://drive.google.com/open?id=1sYG2APPrxxr3RiFvQNZpWnBZ3IrEM5qM

**Comment by cocojoe** [comment]
@Widcket can you try this please

**Comment by cocojoe** [comment]
Thanks, @sbanil we ran through a test and did not have any initial problems. Could you clarify the `close the simulator` step please. What actions are you performing e.g. Quit the Simulator then re-run project? or something else.

It would be worth turning on debugging to see what URL is being hit at this stage, this can be copy/paste to your desktop browser and may give more insight.

Thanks
