### ISSUE TITLE
Use ObjectiveC can't call clearSecssion method

### ISSUE THREAD

**Issue by TryHone** [auth0-samples/auth0-ios-swift-sample#70]
Use ObjectiveC can't call clearSecssion method

**Comment by Widcket** [comment]
Hi @TryHone, apologies for the delay here. Yes, the [wrapper class](https://github.com/auth0/Auth0.swift/blob/master/Auth0/_ObjectiveWebAuth.swift) for Objective-C is lacking that method. Thanks for reporting it! We'll be looking into adding this.

**Comment by Widcket** [comment]
This is now fixed in Auth0.swift [1.30.0](https://github.com/auth0/Auth0.swift/releases/tag/1.30.0).
